[workspace]
members = [
    "crates/compiler",
    "crates/examples",
    "crates/bootloader",
    "crates/kernel",
    "crates/clibc",
    "crates/state",
    "crates/storage",
    "crates/types",
    "crates/vm",
    "aTester",
]

[profile.release]
panic = "abort"
lto = true
